#
# Copyright (c) 2019 Paul Douglas Hahn, CompIntense HPC, LLC
# All rights reserved.
#
#
# See LICENSE file for details.
#
#    This software is distributed WITHOUT ANY WARRANTY; without even 
#    the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR 
#    PURPOSE.  See the above LICENSE notice for more information.
#
#
# Jesu Hilf Mir!
#
#
#
####################################################################
#
#                      *** Start Here ***
#
# You need to make sure the following are defined appropriately for
# your platform: FLTK_DIR, VTK_DIR, VTK_VERSION, and INSTALL_PATH.
#
####################################################################
#
# IMPORTANT: You can explicitly set the path of your FLTK 1.4 installation
# directory here. This is the directory containing "include" and "lib"
# (or "lib64") sub-directories with the FLTK headers and library code,
# resp. needed to compile and link user applications using FLTK.
#
# However, if the utility "fltk-config" is in your $PATH, the following
# should work for you unchanged.
#
FLTK_DIR = $(shell fltk-config --prefix)

#
# IMPORTANT: You can explicitly set the path of your VTK 8.x installation
# directory here. This is the directory containing "include" and "lib"
# (or "lib64") sub-directories with the VTK headers and library code,
# resp. needed to compile and link user applications using VTK.
#
VTK_DIR = /vol1/$(HOSTNAME)/apps/vtk/latest
#VTK_DIR = /usr/local/VTK-8.2.0

VTK_VERSION = 8.2

#
# IMPORTANT: You can explicitly set the installation directory here.
#
INSTALL_PATH = ../installed-vtkFLTK-V8.x-F1.4-$(shell date +'%Y%m%d')


#
# NOTE: Compiler flags.
#
CXXFLAGS += -std=gnu++11 -DUNIX=1 -DVTK_LEGACY_SILENT=1

#
# NOTE: Define VTK_FLTK_BUILD_DEBUG = 1 for verbose runtime debugging output.
#
#CXXFLAGS += -DVTK_FLTK_BUILD_DEBUG=1


#
# NOTE: Compiler options. The default is to build debug.
#
CXX_OPTS = -g
#CXX_OPTS = -g -O2
#CXX_OPTS = -O3


#
# Soli Deo Gloria!
#
