// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef QuadricCutUI_h
#define QuadricCutUI_h
#include <FL/Fl.H>
/* -*- Mode: C++; tab-width: 8; indent-tabs-mode: nil; c-basic-offset: 2 -*-
 *
 * $Id: QuadricCutUI.fl,v 1.4 2004/05/13 18:37:50 xpxqx Exp $
 *
 * Copyright (c) 2002 - 2004 Sean McInerney
 * All rights reserved.
 *
 * See Copyright.txt or http://vtkfltk.sourceforge.net/Copyright.html
 * for details.
 *
 *    This software is distributed WITHOUT ANY WARRANTY; without even 
 *    the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR 
 *    PURPOSE.  See the above copyright notice for more information.
 *
 */
#include "QuadricCutBase.h"
class Fl_VTK_Window;
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Choice.H>
extern void InInCb(Fl_Choice*, void*);
extern void OutInCb(Fl_Choice*, void*);
extern void InOutCb(Fl_Choice*, void*);
extern void OutOutCb(Fl_Choice*, void*);
extern void OnOnCb(Fl_Choice*, void*);
extern void OnInCb(Fl_Choice*, void*);
extern void OnOutCb(Fl_Choice*, void*);
extern void InOnCb(Fl_Choice*, void*);
extern void OutOnCb(Fl_Choice*, void*);
#include <FL/Fl_Box.H>

class VTK_EXPORT QuadricCutUI : public QuadricCutBase {
public:
  static QuadricCutUI* New(void); 
  vtkTypeMacro(QuadricCutUI, QuadricCutBase); 
  QuadricCutUI();
private:
  Fl_Double_Window *mWindow;
  inline void cb_mWindow_i(Fl_Double_Window*, void*);
  static void cb_mWindow(Fl_Double_Window*, void*);
  Fl_VTK_Window *mView;
  static Fl_Menu_Item menu_InIn[];
  static Fl_Menu_Item menu_OutIn[];
  static Fl_Menu_Item menu_InOut[];
  static Fl_Menu_Item menu_OutOut[];
  static Fl_Menu_Item menu_OnOn[];
  static Fl_Menu_Item menu_OnIn[];
  static Fl_Menu_Item menu_OnOut[];
  static Fl_Menu_Item menu_InOn[];
  static Fl_Menu_Item menu_OutOn[];
public:
  Fl_VTK_Window* GetView();
private:
  QuadricCutUI(const QuadricCutUI&); // Not implemented.
  void operator=(const QuadricCutUI&); // Not implemented.
  friend void QuadricCutUIDummy(void); 
};
void QuadricCutUIDummy(void);
#endif
