// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef MCasesUI_h
#define MCasesUI_h
#include <FL/Fl.H>
/* -*- Mode: C++; tab-width: 8; indent-tabs-mode: nil; c-basic-offset: 2 -*-
 *
 * $Id: MCasesUI.fl,v 1.6 2004/05/13 18:37:49 xpxqx Exp $
 *
 * Copyright (c) 2002 - 2004 Sean McInerney
 * All rights reserved.
 *
 * See Copyright.txt or http://vtkfltk.sourceforge.net/Copyright.html
 * for details.
 *
 *    This software is distributed WITHOUT ANY WARRANTY; without even 
 *    the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR 
 *    PURPOSE.  See the above copyright notice for more information.
 *
 */
#include "MCasesBase.h"
class Fl_VTK_Window;
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Value_Input.H>
extern void CaseInputCb(Fl_Value_Input*, void*);
#include <FL/Fl_Roller.H>
extern void CaseRollerCb(Fl_Roller*, void*);
#include <FL/Fl_Light_Button.H>
extern void AntiAliasToggleCb(Fl_Light_Button*, void*);
#include <FL/Fl_Box.H>

class VTK_EXPORT MCasesUI : public MCasesBase {
public:
  static MCasesUI* New(void); 
  vtkTypeMacro(MCasesUI, MCasesBase); 
  MCasesUI();
private:
  Fl_Double_Window *mWindow;
  inline void cb_mWindow_i(Fl_Double_Window*, void*);
  static void cb_mWindow(Fl_Double_Window*, void*);
  Fl_VTK_Window *mView;
public:
  Fl_Value_Input *mCaseInput;
  Fl_Roller *mCaseRoller;
  Fl_VTK_Window* GetView();
  void UpdateView();
private:
  MCasesUI(const MCasesUI&); // Not implemented.
  void operator=(const MCasesUI&); // Not implemented.
  friend void MCasesUIDummy(void); 
};
void MCasesUIDummy(void);
#endif
